import BlogShell from './blog-shell';

export const metadata = {
  title: 'Irrigation Business Software Blog | IrrigationBossPro',
  description: 'Guides on sprinkler repair, irrigation estimating, scheduling, backflow testing, dispatch, invoicing, and running an irrigation business with software.',
};

const silo0 = [
  { title: 'Delivering Backflow Test Certificates to Customers and Cities With Irrigation Software', description: 'See how irrigation software stores and delivers backflow test certificates to customers and water authorities, so proof of passing is one click away every year.', href: '/blogs/backflow-certificate-delivery-customers-irrigation-software' },
  { title: 'How Irrigation Software Tracks Backflow Testing and Certification Deadlines', description: 'See how irrigation software tracks backflow testing due dates, certification deadlines, and renewals so you never miss a required test or lose a recurring customer.', href: '/blogs/backflow-testing-certification-tracking-irrigation-software' },
  { title: 'Card-on-File Billing for Recurring Seasonal Irrigation Service in Irrigation Software', description: 'How card-on-file billing in irrigation software auto-charges winterizations, spring start-ups, and backflow tests so seasonal service gets paid without chasing invoices.', href: '/blogs/card-on-file-recurring-seasonal-billing-irrigation-software' },
  { title: 'Storing Controller, Valve, and Head Details in Property Profiles With Irrigation Software', description: 'Keep controller, valve, and head details in client property profiles so irrigation crews dispatch with the right parts and faster service every season.', href: '/blogs/controller-valve-head-records-property-profiles-irrigation-software' },
  { title: 'Converting Repair Calls Into System Install Leads With Irrigation Software', description: 'How irrigation software turns sprinkler and valve repair calls into new system install bids using property profiles, job notes, and follow-up estimates.', href: '/blogs/converting-repair-calls-into-install-leads-irrigation-software' },
  { title: 'Dispatching and Routing Crews Neighborhood by Neighborhood With Irrigation Software', description: 'See how irrigation software dispatches and routes crews neighborhood by neighborhood so installs, repairs, and seasonal blowouts run tight all day.', href: '/blogs/crew-dispatch-routing-neighborhood-irrigation-software' },
  { title: 'Customer Texts and On-the-Way Alerts for Irrigation Visits in Irrigation Software', description: 'See how irrigation software sends automatic customer texts and on-the-way alerts for installs, repairs, winterizations, and spring start-ups.', href: '/blogs/customer-text-updates-on-the-way-irrigation-software' },
  { title: 'A Day in the Life of an Irrigation Tech Running on Irrigation Software', description: 'Follow an irrigation tech through a full day and see how irrigation software handles routing, parts, estimates, invoicing, and seasonal service from the truck.', href: '/blogs/day-in-the-life-irrigation-tech-irrigation-software' },
  { title: 'Collecting Deposits and Progress Billing on Install Jobs in Irrigation Software', description: 'How irrigation software lets you take deposits up front and bill installs in stages so materials are covered and cash flows before the system is even charged.', href: '/blogs/deposits-progress-billing-installs-irrigation-software' },
  { title: 'Estimating Drip Zone Installs and Conversions in Irrigation Software', description: 'Build accurate line-item bids for drip zone installs and spray-to-drip conversions using irrigation software that tracks parts, labor, and materials.', href: '/blogs/drip-zone-installs-estimating-irrigation-software' },
  { title: 'Beating the First Hard Freeze: Winterization Deadlines in Irrigation Software', description: 'See how IrrigationBossPro tracks every winterization deadline so you blow out every sprinkler system before the first hard freeze hits your route.', href: '/blogs/first-hard-freeze-deadline-irrigation-software' },
  { title: 'Surviving the First Warm Week Rush With Irrigation Software', description: 'See how irrigation software handles the first warm week rush&mdash;batch start-ups, routed crews, line-item repair bids, card-on-file billing, and customer texts.', href: '/blogs/first-warm-week-rush-irrigation-software' },
  { title: 'Running Your Job Board: Turning Unassigned Repairs Into Booked Work With Irrigation Software', description: 'See how the IrrigationBossPro Job Board turns unassigned sprinkler repairs, backflow tests, and start-ups into scheduled, dispatched, invoiced work fast.', href: '/blogs/job-board-unassigned-work-irrigation-software' },
  { title: 'Building Line-Item Bids for New System Installs in Irrigation Software', description: 'How line-item bids in irrigation software turn install estimates into accurate, material-loaded quotes that win jobs and protect margin on new sprinkler systems.', href: '/blogs/line-item-bids-installs-irrigation-software' },
  { title: 'Whiteboard Scheduling vs. Irrigation Software: Where the Hours Go', description: 'See where whiteboard scheduling quietly leaks hours and how irrigation software books, dispatches, and routes installs, repairs, and seasonal work faster.', href: '/blogs/manual-scheduling-vs-irrigation-software' },
  { title: 'Materials and Parts Takeoffs for Irrigation Jobs in Irrigation Software', description: 'Build accurate materials and parts takeoffs for irrigation jobs in IrrigationBossPro so every bid lists heads, valves, controllers, and pipe with no surprises.', href: '/blogs/materials-parts-takeoff-irrigation-software' },
  { title: 'System Audits and Zone-by-Zone Reports With Irrigation Software', description: 'How irrigation software turns a multi-zone system audit into a documented zone-by-zone report, a priced repair estimate, and scheduled follow-up work.', href: '/blogs/multi-zone-system-audit-reports-irrigation-software' },
  { title: 'Smoothing Off-Season Cash Flow With Irrigation Software', description: 'See how irrigation software smooths off-season cash flow with prepaid winterization plans, recurring billing, deposits, and card-on-file payments.', href: '/blogs/off-season-cash-flow-planning-irrigation-software' },
  { title: 'Building a Price Book for Heads, Valves, and Controllers in Irrigation Software', description: 'How a price book in irrigation software locks in pricing for heads, valves, and controllers so estimates are fast, accurate, and consistent.', href: '/blogs/price-book-parts-pricing-irrigation-software' },
  { title: 'The ROI of Irrigation Software: What Contractors Actually Get Back', description: 'A concrete look at the ROI of irrigation software: where contractors win back hours, recover lost seasonal revenue, and protect install margin with one system.', href: '/blogs/roi-of-irrigation-software-for-contractors' },
  { title: 'Turning Start-Ups and Blowouts Into Recurring Revenue With Irrigation Software', description: 'How irrigation software turns one-off spring start-ups and fall blowouts into booked, recurring seasonal revenue you can schedule, dispatch, and bill on autopilot.', href: '/blogs/seasonal-recurring-revenue-irrigation-software' },
  { title: 'Setting Up Irrigation Software in Your First Week: A Practical Onboarding Plan', description: 'A day-by-day plan to set up irrigation software in week one: import clients, build parts lists, load seasonal service, and start estimating and invoicing.', href: '/blogs/setting-up-irrigation-software-first-week' },
  { title: 'Quoting Smart Controller Upgrades With Irrigation Software', description: 'Build accurate smart controller upgrade estimates with line-item parts, labor, and one-tap approvals using IrrigationBossPro irrigation software.', href: '/blogs/smart-controller-upgrade-estimates-irrigation-software' },
  { title: 'Batch-Booking Spring Start-Ups in a Single Pass With Irrigation Software', description: 'See how irrigation software batch-books every spring start-up in one pass, auto-routes crews, and texts customers so the whole list is scheduled fast.', href: '/blogs/spring-start-up-batch-booking-irrigation-software' },
  { title: 'Logging Sprinkler Head Replacements and Parts Used in Irrigation Software', description: 'How irrigation software logs sprinkler head replacements and every part used on a repair job, so estimates, invoices, and inventory stay accurate.', href: '/blogs/sprinkler-head-replacement-jobs-irrigation-software' },
  { title: 'Keeping Trucks Stocked: Parts Replenishment Driven by Irrigation Software', description: 'See how irrigation software ties truck stock to job materials so heads, valves, and controllers get reordered before a tech ever runs short on a route.', href: '/blogs/truck-stock-parts-replenishment-irrigation-software' },
  { title: 'From Two Trucks to Ten: Scaling Irrigation Crews on Irrigation Software', description: 'How irrigation software lets a sprinkler company scale from two trucks to ten crews with bids, materials, the Job Board, dispatch, and seasonal service.', href: '/blogs/two-trucks-to-ten-scaling-crews-irrigation-software' },
  { title: 'A Faster Valve and Wiring Repair Workflow Built on Irrigation Software', description: 'See how irrigation software turns valve and wiring repairs into a fast, repeatable workflow with diagnostics notes, parts, line-item estimates, and card-on-file invoicing.', href: '/blogs/valve-repair-troubleshooting-workflow-irrigation-software' },
  { title: 'Tracking Warranty Work and Callbacks on Installs With Irrigation Software', description: 'See how irrigation software tracks warranty work and callbacks on new system installs so nothing slips, margins hold, and customers stay happy.', href: '/blogs/warranty-callback-tracking-irrigation-software' },
  { title: 'Scheduling Fall Winterizations and Blowouts at Scale With Irrigation Software', description: 'See how irrigation software schedules fall winterizations and blowouts at scale&mdash;recurring jobs, routed crews, card-on-file billing, and customer texts.', href: '/blogs/winterization-blowout-scheduling-irrigation-software' },
];

const silo1 = [
  { title: 'All-in-One vs. Patchwork: Why One Sprinkler Repair Software Wins', description: 'Compare an all-in-one sprinkler repair software to a patchwork of separate tools and see why one connected system wins on estimates, scheduling, and payments.', href: '/blogs/all-in-one-vs-patchwork-sprinkler-repair-software' },
  { title: 'Backflow Testing and Certification Tracking in Sprinkler Repair Software', description: 'Track backflow tests, due dates, and certifications in sprinkler repair software so no annual test slips and every device record stays audit-ready.', href: '/blogs/backflow-testing-and-certification-sprinkler-repair-software' },
  { title: 'Card-on-File and Field Payments in Sprinkler Repair Software', description: 'See how sprinkler repair software stores cards on file and takes field payments so techs collect the moment a valve or head repair is finished.', href: '/blogs/card-on-file-payments-sprinkler-repair-software' },
  { title: 'Logging Controller and Wiring Repairs in Sprinkler Repair Software', description: 'How sprinkler repair software logs controller and wiring repairs with parts, photos, and history so your irrigation crews bill accurately and never lose a fault.', href: '/blogs/controller-and-wiring-repairs-sprinkler-repair-software' },
  { title: 'A Better Repair Customer Experience With Sprinkler Repair Software', description: 'How sprinkler repair software builds a better customer experience on every repair visit &mdash; clear estimates, on-time crews, parts tracking, and fast invoicing.', href: '/blogs/customer-experience-repair-visits-sprinkler-repair-software' },
  { title: 'Keeping Repair Customers Informed With Texts in Sprinkler Repair Software', description: 'How automated text updates in sprinkler repair software keep customers informed from booked to paid &mdash; arrival windows, completion, parts, and invoices.', href: '/blogs/customer-text-updates-sprinkler-repair-software' },
  { title: 'Building Better Diagnostic Work Orders With Sprinkler Repair Software', description: 'See how sprinkler repair software turns vague service calls into clear diagnostic work orders with zone-by-zone notes, parts, photos, and tracked pricing.', href: '/blogs/diagnostic-work-orders-sprinkler-repair-software' },
  { title: 'Dispatching and Routing Repair Crews With Sprinkler Repair Software', description: 'See how sprinkler repair software dispatches and routes repair crews, cuts windshield time, and keeps every valve and head call on schedule all season.', href: '/blogs/dispatch-and-routing-repair-crews-sprinkler-repair-software' },
  { title: 'Handling Emergency and Same-Day Repairs in Sprinkler Repair Software', description: 'Use sprinkler repair software to triage emergency calls, slot same-day repairs, dispatch the nearest tech, and turn a broken line into a paid invoice fast.', href: '/blogs/emergency-and-same-day-repairs-sprinkler-repair-software' },
  { title: 'Your First Week on Sprinkler Repair Software: A Setup Roadmap', description: 'A day-by-day setup roadmap for sprinkler repair software: load parts, build estimate templates, import properties, set up dispatch, and turn on seasonal service.', href: '/blogs/first-week-setup-sprinkler-repair-software' },
  { title: 'How to Choose Sprinkler Repair Software: A Buyers Guide for Irrigation Contractors', description: 'A practical buyers guide to sprinkler repair software for irrigation contractors: what to test for estimates, parts, scheduling, dispatch, invoicing, and seasonal service.', href: '/blogs/how-to-choose-sprinkler-repair-software' },
  { title: 'Invoicing Completed Repairs the Same Day With Sprinkler Repair Software', description: 'How sprinkler repair software turns a finished repair into an itemized, card-on-file invoice the same day &mdash; so you get paid before the truck reaches the next stop.', href: '/blogs/invoicing-completed-repairs-sprinkler-repair-software' },
  { title: 'Running Repair Tickets Off the Job Board in Sprinkler Repair Software', description: 'How the Job Board in sprinkler repair software turns broken-head and valve repair calls into tracked tickets you can schedule, dispatch, and invoice without losing one.', href: '/blogs/job-board-for-repair-tickets-sprinkler-repair-software' },
  { title: 'Line-Item Repair Estimates Done Right in Sprinkler Repair Software', description: 'How line-item repair estimates in sprinkler repair software turn vague service calls into priced, part-loaded quotes that win approval and protect repair margin.', href: '/blogs/line-item-repair-estimates-sprinkler-repair-software' },
  { title: 'Clipboards vs. Sprinkler Repair Software: Why Paper Tickets Cost You Repair Jobs', description: 'Paper repair tickets lose parts, slow billing, and drop callbacks. See how sprinkler repair software captures the job, the materials, and the payment.', href: '/blogs/manual-methods-vs-sprinkler-repair-software' },
  { title: 'The Mobile Field App for Repair Techs in Sprinkler Repair Software', description: 'How a mobile field app for sprinkler repair techs turns the truck into a full office: tickets, parts, photos, estimates, and card-on-file payments from the yard.', href: '/blogs/mobile-field-app-for-repair-techs-sprinkler-repair-software' },
  { title: 'Tracking Heads, Valves, and Parts With Sprinkler Repair Software', description: 'Track heads, valves, controllers, and pipe on every repair with IrrigationBossPro so parts get billed, restocked, and never lost between the truck and the invoice.', href: '/blogs/parts-and-materials-tracking-sprinkler-repair-software' },
  { title: 'Photo Documentation That Prevents Repair Callbacks in Sprinkler Repair Software', description: 'Attach before-and-after repair photos to every job in sprinkler repair software to prevent callbacks, settle disputes, and prove the work was done right.', href: '/blogs/photo-documentation-of-repairs-sprinkler-repair-software' },
  { title: 'Building a Flat-Rate Repair Price Book in Sprinkler Repair Software', description: 'Build a flat-rate repair price book in sprinkler repair software so techs quote head, valve, and controller fixes in seconds &mdash; consistent, profitable, fast.', href: '/blogs/price-book-flat-rate-repairs-sprinkler-repair-software' },
  { title: 'Property and System Profiles That Speed Up Repairs in Sprinkler Repair Software', description: 'See how property and system profiles in sprinkler repair software cut diagnosis time, prefill parts, and turn every repair call into a faster, more profitable visit.', href: '/blogs/property-and-system-profiles-sprinkler-repair-software' },
  { title: 'Recurring Seasonal Service Agreements in Sprinkler Repair Software', description: 'See how sprinkler repair software turns one-off repairs into recurring seasonal service agreements that auto-schedule winterizations, start-ups, and backflow tests.', href: '/blogs/recurring-seasonal-service-agreements-sprinkler-repair-software' },
  { title: 'How Sprinkler Repair Software Cuts Repair Callbacks and Warranty Returns', description: 'See how sprinkler repair software cuts callbacks and warranty returns with detailed work orders, part tracking, and a clear service history on every property.', href: '/blogs/reducing-callbacks-sprinkler-repair-software' },
  { title: 'Job Costing Repairs and Protecting Margins With Sprinkler Repair Software', description: 'See how sprinkler repair software job-costs every repair, tracks parts and labor, and protects margins so each valve and head fix actually turns a profit.', href: '/blogs/repair-job-costing-and-margins-sprinkler-repair-software' },
  { title: 'The ROI of Sprinkler Repair Software: What the Right Platform Pays Back', description: 'How sprinkler repair software pays for itself: faster estimates, fewer missed parts, tighter scheduling, recurring seasonal revenue, and card-on-file invoicing.', href: '/blogs/roi-of-sprinkler-repair-software' },
  { title: 'Scaling From One Repair Truck to a Fleet With Sprinkler Repair Software', description: 'Grow from one repair truck to a fleet using sprinkler repair software that standardizes estimates, parts, scheduling, dispatch, and invoicing as you add crews.', href: '/blogs/scaling-from-one-truck-to-many-sprinkler-repair-software' },
  { title: 'Scheduling Repair Calls That Keep Crews Busy With Sprinkler Repair Software', description: 'See how sprinkler repair software schedules and routes repair calls, fills gaps between jobs, and keeps your irrigation crews productive every single day.', href: '/blogs/scheduling-repair-calls-sprinkler-repair-software' },
  { title: 'Batch-Scheduling Spring Start-Ups With Sprinkler Repair Software', description: 'Batch-schedule spring start-ups in sprinkler repair software so every winterized system gets reactivated, routed, and invoiced without manual call-downs.', href: '/blogs/spring-startup-batch-scheduling-sprinkler-repair-software' },
  { title: 'Sprinkler Repair Software: The Complete Guide for Irrigation Service Pros', description: 'A complete guide to sprinkler repair software: how it handles estimates, parts, scheduling, dispatch, invoicing, and recurring seasonal irrigation work.', href: '/blogs/sprinkler-repair-software-complete-guide' },
  { title: 'Managing Valve and Head Replacement Jobs in Sprinkler Repair Software', description: 'How sprinkler repair software manages valve and head replacement jobs end to end &mdash; line-item estimates, parts, scheduling, dispatch, invoicing, and card payments.', href: '/blogs/valve-and-head-replacement-jobs-sprinkler-repair-software' },
  { title: 'Scheduling Fall Winterizations and Blowouts in Sprinkler Repair Software', description: 'How sprinkler repair software schedules fall winterizations and blowouts, routes crews, and bills card-on-file so no irrigation customer gets missed before freeze.', href: '/blogs/winterization-blowout-scheduling-sprinkler-repair-software' },
];

const silo2 = [
  { title: 'Auto-Rebooking Seasonal Customers Every Year With Irrigation Scheduling Software', description: 'Stop rebuilding your service list each season&mdash;see how irrigation scheduling software auto-rebooks recurring winterizations and start-ups year after year.', href: '/blogs/auto-rebook-seasonal-customers-irrigation-scheduling-software' },
  { title: 'Batch Scheduling Hundreds of Spring Startups With Irrigation Scheduling Software', description: 'See how irrigation scheduling software batch-books hundreds of spring start-ups in minutes&mdash;auto-loading recurring jobs, routing crews, and texting customers.', href: '/blogs/batch-scheduling-spring-startups-irrigation-scheduling-software' },
  { title: 'Scheduling Controller Upgrades and Smart Timer Installs in Irrigation Scheduling Software', description: 'See how irrigation scheduling software bids, schedules, and bills controller upgrades and smart timer installs&mdash;materials, dispatch, and payment in one flow.', href: '/blogs/controller-replacement-upgrade-scheduling-irrigation-scheduling-software' },
  { title: 'Crew Capacity Planning: Booking Only What Your Trucks Can Finish in Irrigation Scheduling Software', description: 'See how irrigation scheduling software caps each crew at real capacity&mdash;sizing jobs, routing trucks, and booking only the work your day can actually finish.', href: '/blogs/crew-capacity-planning-irrigation-scheduling-software' },
  { title: 'Keeping Customers in the Loop With Scheduling Texts From Irrigation Scheduling Software', description: 'How irrigation scheduling software texts customers their service window, day-of reminders, and reschedules automatically&mdash;cutting no-access trips and call volume.', href: '/blogs/customer-text-updates-scheduling-irrigation-scheduling-software' },
  { title: 'Running the Day From the Dispatch Board and Job Board in Irrigation Scheduling Software', description: 'See how the dispatch board and Job Board in irrigation scheduling software let you assign crews, route jobs, and run a full day of sprinkler work at a glance.', href: '/blogs/dispatch-board-job-board-irrigation-scheduling-software' },
  { title: 'Rebalancing the Day by Dragging Jobs Between Crews in Irrigation Scheduling Software', description: 'Drag irrigation jobs between crews on the live Job Board to rebalance the day&mdash;reroute repairs, winterizations, and start-ups in seconds without phone calls.', href: '/blogs/drag-jobs-between-crews-irrigation-scheduling-software' },
  { title: 'Cutting Repair Callbacks With Better-Documented Scheduled Visits in Irrigation Scheduling Software', description: 'See how irrigation scheduling software documents every scheduled visit&mdash;parts, zones, and photos&mdash;so first trips are complete and repair callbacks disappear.', href: '/blogs/drip-zone-and-repair-callbacks-irrigation-scheduling-software' },
  { title: 'Fitting Emergency Valve and Head Repairs Into a Full Day With Irrigation Scheduling Software', description: 'How irrigation scheduling software slots emergency valve and head repairs into an already-booked day without blowing up your crews&apos; routes or service calls.', href: '/blogs/emergency-repair-fit-in-jobs-irrigation-scheduling-software' },
  { title: 'Turning Line-Item Bids and Parts Lists Into Calendar Slots With Irrigation Scheduling Software', description: 'See how irrigation scheduling software turns approved line-item bids and parts lists straight into routed, crew-ready calendar slots&mdash;no retyping required.', href: '/blogs/estimating-parts-bids-into-the-calendar-irrigation-scheduling-software' },
  { title: 'Filling the Shoulder-Season Gaps in Your Calendar With Irrigation Scheduling Software', description: 'See how irrigation scheduling software fills slow spring and fall gaps&mdash;surfacing repairs, backflow tests, and upgrades so crews stay booked between the rush.', href: '/blogs/filling-shoulder-season-gaps-irrigation-scheduling-software' },
  { title: 'Your First Week on Irrigation Scheduling Software: A Setup Roadmap', description: 'A day-by-day first-week roadmap for setting up irrigation scheduling software: properties, parts library, estimates, the Job Board, dispatch, and seasonal service.', href: '/blogs/first-week-setup-irrigation-scheduling-software' },
  { title: 'Five Scheduling Mistakes Irrigation Scheduling Software Fixes Overnight', description: 'Five scheduling mistakes that bleed irrigation contractors dry&mdash;double-booked crews, no-access trips, blown seasonal rebooks&mdash;and how irrigation scheduling software fixes each one.', href: '/blogs/five-scheduling-mistakes-irrigation-scheduling-software-fixes' },
  { title: 'Paper Calendar vs. Irrigation Scheduling Software: Why Contractors Make the Switch', description: 'See why irrigation contractors trade the paper calendar for scheduling software that handles installs, repairs, winterizations, and start-ups automatically.', href: '/blogs/manual-calendar-vs-irrigation-scheduling-software' },
  { title: 'A Smoother Morning Dispatch Routine With Irrigation Scheduling Software', description: 'See how irrigation scheduling software turns chaotic morning dispatch into a five-minute routine that routes crews, loads parts, and confirms jobs.', href: '/blogs/morning-dispatch-routine-irrigation-scheduling-software' },
  { title: 'Neighborhood Clustering: Scheduling Tight Routes With Irrigation Scheduling Software', description: 'See how irrigation scheduling software clusters jobs by neighborhood so crews drive less, finish more winterizations, start-ups, and repairs each day.', href: '/blogs/neighborhood-clustering-routes-irrigation-scheduling-software' },
  { title: 'Loading the Right Heads and Valves Before Every Scheduled Job in Irrigation Scheduling Software', description: 'How irrigation scheduling software ties parts &mdash; heads, valves, controllers &mdash; to each scheduled job so your crews leave the shop with the right materials on the truck.', href: '/blogs/parts-on-truck-before-scheduled-job-irrigation-scheduling-software' },
  { title: 'Property Profiles and Zone Maps That Make Every Scheduled Visit Faster', description: 'Build property profiles and zone maps in IrrigationBossPro so every winterization, start-up, and repair visit starts with the parts and history your crew needs.', href: '/blogs/property-profiles-zone-maps-irrigation-scheduling-software' },
  { title: 'From Approved Estimate to Scheduled Crew in One Click With Irrigation Scheduling Software', description: 'See how irrigation scheduling software turns an approved sprinkler estimate into a scheduled, dispatched crew in one click&mdash;no re-typing parts, dates, or addresses.', href: '/blogs/quote-to-scheduled-job-irrigation-scheduling-software' },
  { title: 'Handling a Rain Day: Mass Rescheduling Without Phone Tag in Irrigation Scheduling Software', description: 'How irrigation scheduling software lets you move a full rained-out day of installs, repairs, and start-ups to a new date and text every customer at once.', href: '/blogs/rain-delay-mass-reschedule-irrigation-scheduling-software' },
  { title: 'The ROI of Irrigation Scheduling Software: What an Organized Calendar Is Worth', description: 'See the real ROI of irrigation scheduling software: more installs and service calls per day, fewer dropped winterizations, faster invoicing, and paid-on-time jobs.', href: '/blogs/roi-of-irrigation-scheduling-software' },
  { title: 'Scaling From One Crew to Five Without Chaos Using Irrigation Scheduling Software', description: 'See how irrigation scheduling software lets you grow from one crew to five with shared job boards, dispatch, materials tracking, and seasonal recurring work.', href: '/blogs/scaling-from-one-to-five-crews-irrigation-scheduling-software' },
  { title: 'Schedule-Driven Invoicing and Card-on-File Payments in Irrigation Scheduling Software', description: 'How irrigation scheduling software turns completed jobs into invoices automatically and collects card-on-file payments the day the crew closes the work.', href: '/blogs/schedule-driven-invoicing-card-on-file-irrigation-scheduling-software' },
  { title: 'Scheduling Backflow Tests Before the Deadline With Irrigation Scheduling Software', description: 'Learn how irrigation scheduling software groups backflow tests by due date and route so your certified tester clears every deadline before the city sends a notice.', href: '/blogs/scheduling-backflow-test-deadlines-irrigation-scheduling-software' },
  { title: 'Scheduling Multi-Day System Installs as Projects in Irrigation Scheduling Software', description: 'Learn how irrigation scheduling software lets you plan multi-day sprinkler installs as projects with phased crews, materials, and billing milestones.', href: '/blogs/scheduling-multi-day-install-projects-irrigation-scheduling-software' },
  { title: 'Putting Full Service History on Every Scheduled Stop in Irrigation Scheduling Software', description: 'How irrigation scheduling software puts each property&apos;s full service history&mdash;zones, parts, past repairs, and backflow tests&mdash;right on the scheduled stop.', href: '/blogs/service-history-on-the-schedule-irrigation-scheduling-software' },
  { title: 'Why Spreadsheets Overbook Your Crews and Irrigation Scheduling Software Does Not', description: 'See why spreadsheets quietly overbook irrigation crews and how scheduling software enforces real capacity, drive time, and parts before a job ever lands.', href: '/blogs/spreadsheet-overbooking-vs-irrigation-scheduling-software' },
  { title: 'How a Waiting List Tames Startup and Winterization Season in Irrigation Scheduling Software', description: 'How a waiting list in irrigation scheduling software queues every spring start-up and fall blowout so seasonal crunch becomes a routed, dispatched plan.', href: '/blogs/waiting-list-startup-winterization-irrigation-scheduling-software' },
  { title: 'Building Efficient Winterization Blowout Routes in Irrigation Scheduling Software', description: 'Use irrigation scheduling software to batch fall blowouts by zip, route crews tightly, and bill on the spot so your winterization season runs lean.', href: '/blogs/winterization-blowout-routes-irrigation-scheduling-software' },
  { title: 'Building a Year-Round Scheduling Rhythm Around the Irrigation Seasons', description: 'See how irrigation scheduling software turns the spring start-up, summer repair, and fall winterization seasons into one steady, predictable year-round work rhythm.', href: '/blogs/year-round-schedule-rhythm-irrigation-scheduling-software' },
];

const silo3 = [
  { title: 'Pricing Labor Accurately in Your Irrigation Estimating Software', description: 'Learn how irrigation estimating software prices labor accurately on installs, repairs, and seasonal work so every bid protects your crew hours and your margin.', href: '/blogs/accurate-labor-pricing-irrigation-estimating-software' },
  { title: 'Estimating Backflow Testing and Certification Work in Your Software', description: 'Learn how irrigation estimating software builds fast, accurate bids for backflow testing, certification, and failed-device repairs so every test turns a profit.', href: '/blogs/backflow-testing-estimates-irrigation-estimating-software' },
  { title: 'Building Line-Item Irrigation Estimates Fast With Estimating Software', description: 'How irrigation estimating software builds fast, line-item bids from a saved materials catalog so you quote sprinkler jobs accurately and convert them to scheduled work.', href: '/blogs/build-line-item-irrigation-estimates-fast' },
  { title: 'Handling Change Orders and Add-Ons Inside Irrigation Estimating Software', description: 'See how irrigation estimating software handles change orders and add-ons mid-job so every extra zone, head, or valve gets quoted, approved, and billed correctly.', href: '/blogs/change-orders-add-ons-irrigation-estimating-software' },
  { title: 'Common Irrigation Bidding Mistakes Estimating Software Helps You Avoid', description: 'How irrigation estimating software stops the bidding mistakes that quietly drain sprinkler jobs: missed parts, guessed labor, stale pricing, and lump-sum quotes.', href: '/blogs/common-estimating-mistakes-irrigation-estimating-software' },
  { title: 'Estimating Controllers, Zones, and Wiring With Irrigation Software', description: 'Price controllers, zones, valves, and wire by the line item with irrigation estimating software that builds accurate sprinkler bids in minutes.', href: '/blogs/controller-and-zone-pricing-irrigation-estimating-software' },
  { title: 'Getting Estimates Approved Faster With E-Signatures and Deposits', description: 'See how IrrigationBossPro lets clients e-sign sprinkler install and repair estimates and pay a deposit online, so jobs get approved and scheduled the same day.', href: '/blogs/e-signature-estimate-approval-irrigation-estimating-software' },
  { title: 'From Estimate to Invoice With Card-on-File in Irrigation Estimating Software', description: 'See how irrigation estimating software carries a line-item bid straight through to a paid invoice with card-on-file payments and no rekeying.', href: '/blogs/estimate-to-invoice-irrigation-estimating-software' },
  { title: 'From Estimate to the Job Board: Turning Bids Into Scheduled Work', description: 'See how IrrigationBossPro turns a signed line-item irrigation bid into scheduled, dispatched crew work on the Job Board in a few clicks.', href: '/blogs/estimate-to-job-board-irrigation-estimating-software' },
  { title: 'Cutting Bid Turnaround Time With Irrigation Estimating Software', description: 'How irrigation estimating software cuts bid turnaround from days to minutes with a parts price book, reusable templates, and instant customer approval and scheduling.', href: '/blogs/faster-bid-turnaround-irrigation-estimating-software' },
  { title: 'Your First Week With Irrigation Estimating Software: A Setup Walkthrough', description: 'A day-by-day first-week setup walkthrough for irrigation estimating software so you can build accurate bids, load parts, and schedule jobs fast.', href: '/blogs/first-week-setup-irrigation-estimating-software' },
  { title: 'Good-Better-Best Irrigation Estimates That Win More Installs', description: 'How irrigation estimating software builds good-better-best tiered install bids from one materials catalog so customers pick a package and you close more sprinkler systems.', href: '/blogs/good-better-best-irrigation-estimating-software' },
  { title: 'How to Choose Irrigation Estimating Software That Fits Your Sprinkler Business', description: 'How to choose irrigation estimating software: the features sprinkler contractors need to build material-loaded bids that win jobs and protect install margin.', href: '/blogs/how-to-choose-irrigation-estimating-software' },
  { title: 'Irrigation Estimating Software: The Complete Guide for Sprinkler Contractors', description: 'Irrigation estimating software builds line-item bids with heads, valves, and controllers, then turns the accepted estimate into a scheduled, invoiced job.', href: '/blogs/irrigation-estimating-software-complete-guide' },
  { title: 'Hand-Written Bids vs. Irrigation Estimating Software: An Honest Comparison', description: 'An honest comparison of hand-written sprinkler bids and irrigation estimating software for pricing heads, valves, controllers, pipe, and seasonal service work.', href: '/blogs/manual-vs-software-irrigation-estimating' },
  { title: 'Pricing Heads, Valves, Pipe, and Parts Right in Irrigation Estimating Software', description: 'Price heads, valves, pipe, and parts right in IrrigationBossPro so every irrigation estimate protects your margin and turns into a loaded truck and a paid invoice.', href: '/blogs/materials-parts-pricing-irrigation-estimating-software' },
  { title: 'Estimating Large, Multi-Zone Commercial Irrigation Projects', description: 'See how irrigation estimating software builds accurate, line-item bids for large multi-zone commercial systems so big installs stay profitable and on budget.', href: '/blogs/multi-zone-large-property-estimates-irrigation-estimating-software' },
  { title: 'Bidding New Sprinkler System Installs With Irrigation Estimating Software', description: 'Build accurate new sprinkler system install bids with irrigation estimating software that prices heads, valves, controllers, and pipe by the line item.', href: '/blogs/new-system-install-bids-irrigation-estimating-software' },
  { title: 'Writing On-Site Estimates From the Truck With Mobile Estimating Software', description: 'How mobile irrigation estimating software lets you build line-item bids for installs, repairs, and backflow work from the truck before you pull away.', href: '/blogs/on-site-estimates-mobile-irrigation-estimating-software' },
  { title: 'Sending Professional, Branded Estimates That Build Trust', description: 'How irrigation estimating software sends clean, branded, line-item sprinkler bids that win trust, get signed faster, and convert straight into scheduled jobs.', href: '/blogs/professional-branded-estimates-irrigation-estimating-software' },
  { title: 'Using Property Profiles to Speed Up Repeat Irrigation Estimates', description: 'See how irrigation estimating software uses saved property profiles to rebuild repeat sprinkler bids in seconds with the right zones, heads, valves, and parts.', href: '/blogs/property-profiles-faster-estimates-irrigation-estimating-software' },
  { title: 'Protecting Your Margins on Every Bid With Estimating Software', description: 'How line-item irrigation estimating software protects your margin on every bid by pricing heads, valves, controllers, pipe, and backflow parts and labor accurately.', href: '/blogs/protecting-margins-irrigation-estimating-software' },
  { title: 'The ROI of Irrigation Estimating Software for a Sprinkler Business', description: 'See the real ROI of irrigation estimating software: faster bids, accurate parts and labor pricing, fewer margin leaks, and more sprinkler jobs won.', href: '/blogs/roi-of-irrigation-estimating-software' },
  { title: 'Building a Saved Price Book in Irrigation Estimating Software', description: 'How a saved price book in irrigation estimating software turns repeatable line items into fast, consistent, profitable bids for installs and repairs.', href: '/blogs/saved-price-book-irrigation-estimating-software' },
  { title: 'Scaling Crews While Keeping Estimates Consistent and Accurate', description: 'How irrigation estimating software keeps every crew bidding sprinkler jobs from one shared catalog so estimates stay consistent and accurate as you add trucks.', href: '/blogs/scaling-crews-consistent-estimates-irrigation-estimating-software' },
  { title: 'Building Seasonal Service Packages and Recurring Quotes in Your Software', description: 'Bundle winterizations, spring start-ups, and backflow tests into seasonal packages with recurring quotes that auto-bill and auto-schedule in IrrigationBossPro.', href: '/blogs/seasonal-service-packages-irrigation-estimating-software' },
  { title: 'Estimating Spring Start-Ups and Seasonal Tune-Ups in Your Software', description: 'Build fast, accurate spring start-up and seasonal tune-up estimates in IrrigationBossPro, with saved line items, parts pricing, and recurring scheduling.', href: '/blogs/spring-startup-estimates-irrigation-estimating-software' },
  { title: 'Pricing Sprinkler and Valve Repairs With Irrigation Estimating Software', description: 'How irrigation estimating software prices sprinkler and valve repairs part-by-part, protecting margin and turning approved bids into dispatched, invoiced jobs.', href: '/blogs/sprinkler-repair-estimates-irrigation-estimating-software' },
  { title: 'Boosting Your Estimate Win Rate With Automated Follow-Up Texts', description: 'See how IrrigationBossPro sends automated follow-up texts on open irrigation bids so more estimates turn into booked, scheduled, paid jobs.', href: '/blogs/win-rate-follow-up-irrigation-estimating-software' },
  { title: 'Quoting Fall Winterizations and Blowouts With Estimating Software', description: 'Build fast, accurate fall winterization and blowout estimates by zone and PSI, then auto-bill the whole route with IrrigationBossPro estimating software.', href: '/blogs/winterization-blowout-estimates-irrigation-estimating-software' },
];

const silo4 = [
  { title: 'Why All-in-One Backflow Testing Software Beats a Patchwork of Tools', description: 'See why all-in-one backflow testing software beats a patchwork of spreadsheets, calendars, and apps for scheduling, certificates, repairs, and recurring billing.', href: '/blogs/all-in-one-backflow-testing-software-versus-patchwork-tools' },
  { title: 'Backflow Testing Software: The Complete Guide for Irrigation Contractors', description: 'A complete guide to backflow testing software for irrigation contractors: track devices, schedule tests, store certificates, and bill recurring renewals automatically.', href: '/blogs/backflow-testing-software-complete-guide' },
  { title: 'Bundling Backflow Tests With Spring Start-Ups in Backflow Testing Software', description: 'See how backflow testing software bundles annual backflow tests into spring start-up visits so one trip earns two line items and zero wasted windshield time.', href: '/blogs/bundling-backflow-tests-with-spring-startups-backflow-testing-software' },
  { title: 'Collecting Backflow Test Payments With Card-on-File Software', description: 'Store a card on file and auto-charge backflow test fees the moment the job closes&mdash;no chasing checks. See how card-on-file software speeds irrigation cash flow.', href: '/blogs/card-on-file-payments-backflow-testing-software' },
  { title: 'Serving Commercial Property Managers With Backflow Testing Software', description: 'See how backflow testing software helps you serve commercial property managers &mdash; multi-device tracking, scheduling, certificates, and consolidated invoicing.', href: '/blogs/commercial-property-manager-backflow-testing-software' },
  { title: 'A Better Customer Experience for Backflow Certification With Software', description: 'See how backflow testing software gives customers reminders, clean estimates, fast scheduling, and instant certificates so annual certification feels effortless.', href: '/blogs/customer-experience-backflow-certification-backflow-testing-software' },
  { title: 'Keeping Customers Informed With Texts From Backflow Testing Software', description: 'See how backflow testing software keeps customers informed with automatic texts &mdash; reminders, on-the-way alerts, pass results, and certificate delivery.', href: '/blogs/customer-texts-backflow-test-updates-backflow-testing-software' },
  { title: 'A Day in the Field With Backflow Testing Software', description: 'Walk through a full day of backflow testing with software that handles scheduling, device records, test results, certificates, and invoicing from one place.', href: '/blogs/daily-workflow-backflow-testing-software' },
  { title: 'Routing Backflow Test Days With Backflow Testing Software', description: 'See how backflow testing software groups due devices by neighborhood and dispatches a tight route so your tester clears more devices per day with less windshield time.', href: '/blogs/dispatch-routing-backflow-test-routes-backflow-testing-software' },
  { title: 'Estimating Backflow Repairs and Rebuilds With Backflow Testing Software', description: 'See how backflow testing software builds fast, accurate line-item estimates for failed-device repairs, rebuild kits, and full replacements so every repair stays profitable.', href: '/blogs/estimating-backflow-repairs-backflow-testing-software' },
  { title: 'How to Choose Backflow Testing Software for Your Irrigation Business', description: 'How to choose backflow testing software for your irrigation business: device tracking, due-date reminders, routing, certificates, and one-click invoicing that pays.', href: '/blogs/how-to-choose-backflow-testing-software' },
  { title: 'Invoicing Backflow Tests Same Day With Backflow Testing Software', description: 'See how backflow testing software lets your irrigation crew invoice and collect for every backflow test the same day the tech finishes the job.', href: '/blogs/invoicing-backflow-tests-backflow-testing-software' },
  { title: 'Filling the Job Board With Backflow Tests Using Backflow Testing Software', description: 'See how backflow testing software fills your Job Board with due tests, certification renewals, and failed-device repairs so no assembly gets missed.', href: '/blogs/job-board-backflow-test-assignments-backflow-testing-software' },
  { title: 'Line-Item Bids for Backflow Assembly Replacement in Backflow Testing Software', description: 'See how backflow testing software builds clean line-item bids for full assembly replacements&mdash;new device, fittings, and certified labor&mdash;so every swap stays profitable.', href: '/blogs/line-item-bids-backflow-assembly-replacement-backflow-testing-software' },
  { title: 'Spreadsheets vs. Backflow Testing Software for Tracking Renewals', description: 'Why spreadsheets fail at tracking backflow test renewals and how purpose-built software auto-schedules, reminds, and bills every annual certification.', href: '/blogs/manual-vs-backflow-testing-software-tracking-renewals' },
  { title: 'The Mobile Field App in Backflow Testing Software', description: 'See how the mobile field app in backflow testing software lets testers log gauge readings, pass results, and certificates from the truck.', href: '/blogs/mobile-field-app-backflow-testing-software' },
  { title: 'Online Booking for Backflow Tests With Backflow Testing Software', description: 'See how backflow testing software with online booking lets customers schedule their annual backflow test themselves and lands jobs straight on your calendar.', href: '/blogs/online-booking-backflow-tests-backflow-testing-software' },
  { title: 'Tracking Backflow Devices and Repair Parts in Backflow Testing Software', description: 'Track every backflow device, serial number, and repair part in backflow testing software so retests, rebuilds, and reorders never slip through the cracks.', href: '/blogs/parts-tracking-backflow-devices-backflow-testing-software' },
  { title: 'Photo and Gauge Documentation in Backflow Testing Software', description: 'See how backflow testing software captures gauge readings and on-site photos so every certification is documented, defensible, and ready to file.', href: '/blogs/photo-test-documentation-backflow-testing-software' },
  { title: 'Property Profiles and Device Records in Backflow Testing Software', description: 'See how property profiles and device records in backflow testing software keep every assembly, location, and test history organized for fast recertification.', href: '/blogs/property-profiles-device-records-backflow-testing-software' },
  { title: 'Syncing Backflow Test Billing to QuickBooks With Backflow Testing Software', description: 'Push backflow test invoices, payments, and parts straight into QuickBooks&mdash;no double entry. See how backflow testing software keeps irrigation books clean.', href: '/blogs/quickbooks-backflow-billing-backflow-testing-software' },
  { title: 'Never Miss a Renewal: Recurring Certification Reminders in Backflow Testing Software', description: 'See how backflow testing software fires recurring certification reminders so every annual test rebooks itself and you never lose a renewal or a customer.', href: '/blogs/recurring-backflow-certification-reminders-backflow-testing-software' },
  { title: 'Cutting No-Shows on Backflow Appointments With Backflow Testing Software', description: 'How backflow testing software cuts no-shows with automatic appointment texts, day-before reminders, and easy reschedules that keep your certification routes full.', href: '/blogs/reducing-no-shows-backflow-appointments-backflow-testing-software' },
  { title: 'Tracking Backflow Test KPIs and Reports in Backflow Testing Software', description: 'See how backflow testing software tracks the KPIs and reports that matter — pass rates, tester productivity, certificate compliance, and revenue per test.', href: '/blogs/reporting-kpis-backflow-testing-software' },
  { title: 'The ROI of Backflow Testing Software for Irrigation Contractors', description: 'See the real ROI of backflow testing software: never miss a renewal, batch-schedule annual tests, deliver certificates fast, and bill every test on time.', href: '/blogs/roi-of-backflow-testing-software-irrigation' },
  { title: 'Scaling From One Tester to Several Crews With Backflow Testing Software', description: 'Backflow testing software lets you grow from a solo tester to several crews without losing certs, deadlines, or revenue across the season.', href: '/blogs/scaling-backflow-testing-crews-backflow-testing-software' },
  { title: 'Scheduling Annual Backflow Tests With Backflow Testing Software', description: 'Backflow testing software auto-schedules annual tests, dispatches techs by route, and bills on site so no certification deadline ever slips through the cracks.', href: '/blogs/scheduling-annual-backflow-tests-backflow-testing-software' },
  { title: 'Setting Up Backflow Testing Software in Your First Week', description: 'A practical first-week setup plan for backflow testing software: import devices, build test estimates, schedule recurring certifications, and turn on customer texts.', href: '/blogs/setting-up-backflow-testing-software-first-week' },
  { title: 'Submitting Backflow Test Reports to the Water Authority With Software', description: 'See how backflow testing software fills out water authority test reports, captures gauge readings, and submits certified results on time without paper forms.', href: '/blogs/water-authority-report-submission-backflow-testing-software' },
  { title: 'Coordinating Fall Winterization and Backflow Protection With Software', description: 'See how backflow testing software ties fall winterizations to backflow protection so devices, blowouts, and compliance stay coordinated all season long.', href: '/blogs/winterization-backflow-protection-backflow-testing-software' },
];

const silo5 = [
  { title: 'Why All-in-One Irrigation Crew & Dispatch Software Beats a Patchwork of Tools', description: 'See why all-in-one irrigation crew and dispatch software beats stitching together separate apps for scheduling, routing, estimates, invoicing, and seasonal work.', href: '/blogs/all-in-one-irrigation-crew-dispatch-software-vs-patchwork' },
  { title: 'Assigning Jobs and Balancing Crew Workloads in Irrigation Dispatch Software', description: 'See how irrigation dispatch software assigns jobs and balances crew workloads, so every truck runs a full, fair day of installs, repairs, and seasonal service.', href: '/blogs/assigning-jobs-balancing-crew-workloads-irrigation-software' },
  { title: 'Dispatching Backflow Testing and Certification Routes With Irrigation Software', description: 'See how irrigation software batches backflow tests into tight routes, dispatches your certified tester, and turns annual certifications into easy recurring revenue.', href: '/blogs/backflow-testing-dispatch-scheduling-irrigation-software' },
  { title: 'Smart Crew Routing That Cuts Drive Time on Irrigation Service Days', description: 'See how IrrigationBossPro routes crews by location so service days have less drive time, more billable stops, and lower fuel costs for your sprinkler business.', href: '/blogs/crew-routing-fuel-savings-irrigation-dispatch-software' },
  { title: 'Crew Time Tracking and Job Costing on Every Dispatched Irrigation Visit', description: 'See how IrrigationBossPro tracks crew time and job costs on every dispatched sprinkler visit so installs, repairs, and seasonal service stay profitable.', href: '/blogs/crew-time-tracking-job-costing-irrigation-dispatch-software' },
  { title: 'On-My-Way Texts: Keeping Customers Posted From the Dispatch Board', description: 'See how irrigation dispatch software fires on-my-way and arrival-window texts straight from the board, cutting no-shows and call-backs on every service day.', href: '/blogs/customer-texts-on-the-way-irrigation-dispatch-software' },
  { title: 'Dispatch KPIs and Reporting That Keep Irrigation Crews Productive', description: 'See how IrrigationBossPro dispatch KPIs and reporting track jobs per crew, drive time, repeat visits, and seasonal revenue to keep sprinkler crews productive.', href: '/blogs/dispatch-kpis-reporting-irrigation-crew-software' },
  { title: 'Before-and-After Photos: Documenting Every Dispatched Irrigation Job', description: 'See how IrrigationBossPro lets crews attach before-and-after photos to every dispatched irrigation job for proof, faster invoicing, and fewer disputes.', href: '/blogs/dispatch-photos-documentation-irrigation-crew-software' },
  { title: 'Batch-Dispatching Fall Winterizations and Blowouts Before the Freeze', description: 'See how irrigation dispatch software batches fall winterization and blowout jobs by neighborhood, routes crews tight, and bills every stop before the first hard freeze.', href: '/blogs/fall-winterization-blowout-dispatch-irrigation-software' },
  { title: 'How to Choose Irrigation Crew & Dispatch Software: A Buyer\'s Guide', description: 'A practical buyer\'s guide to choosing irrigation crew and dispatch software: what to check for estimates, materials, scheduling, dispatch, invoicing, and seasonal work.', href: '/blogs/how-to-choose-irrigation-crew-dispatch-software' },
  { title: 'Invoicing and Card-on-File Payments the Moment a Crew Closes a Job', description: 'See how IrrigationBossPro turns a closed irrigation job into an invoice and a card-on-file charge the same day, so crews finish work and the money is collected.', href: '/blogs/invoicing-card-on-file-from-completed-dispatch-irrigation-software' },
  { title: 'Irrigation Crew & Dispatch Software: The Complete Guide for Sprinkler Contractors', description: 'How irrigation crew & dispatch software ties estimates, parts, scheduling, routing, and seasonal winterization into one system for sprinkler contractors.', href: '/blogs/irrigation-crew-dispatch-software-complete-guide' },
  { title: 'Working the Job Board: Turning Pending Requests Into Dispatched Crews', description: 'See how irrigation crew & dispatch software turns pending repair, install, and seasonal requests into scheduled, routed, dispatched crews fast.', href: '/blogs/job-board-pending-work-irrigation-crew-dispatch-software' },
  { title: 'How Line-Item Estimates Flow Straight Into Crew Dispatch', description: 'See how IrrigationBossPro turns line-item irrigation estimates into scheduled, dispatched jobs with the right parts, crew, and pricing already attached.', href: '/blogs/line-item-estimates-feed-dispatch-irrigation-software' },
  { title: 'The Live Dispatch Board: Seeing Every Crew and Job in Irrigation Software', description: 'How a live dispatch board in irrigation software shows every crew, install, repair, and seasonal job in one view so you can route and reassign in real time.', href: '/blogs/live-dispatch-board-irrigation-crew-software' },
  { title: 'Managing Multiple Irrigation Crews and Routes From One Dispatch Board', description: 'How one dispatch board lets an irrigation business build, assign, and send routes to multiple crews for installs, repairs, winterizations, and start-ups.', href: '/blogs/managing-multiple-irrigation-crews-routes-dispatch-software' },
  { title: 'Manual Dispatch vs. Software: The Real Cost for Irrigation Crews', description: 'See the true cost of manual dispatch for irrigation crews and how scheduling, routing, and dispatch software pays for itself in saved windshield time.', href: '/blogs/manual-dispatch-vs-software-irrigation-crews' },
  { title: 'The Mobile Dispatch App Your Irrigation Technicians Actually Use', description: 'How IrrigationBossPro pushes each tech a route with stops, property profiles, valve and head notes, parts lists, and on-site invoicing right on their phone.', href: '/blogs/mobile-dispatch-app-irrigation-technicians' },
  { title: 'Getting the Right Heads, Valves, and Controllers on the Truck Before Dispatch', description: 'See how irrigation dispatch software puts the exact heads, valves, and controllers on each truck before dispatch so crews finish jobs in one trip.', href: '/blogs/parts-and-materials-on-the-truck-irrigation-dispatch-software' },
  { title: 'Property Profiles and System History That Travel With the Crew', description: 'Property profiles and full system history in irrigation dispatch software let your crew arrive knowing the zones, parts, and past work on every sprinkler job.', href: '/blogs/property-profiles-system-history-irrigation-dispatch-software' },
  { title: 'Real-Time Crew Tracking: Knowing Where Every Irrigation Truck Is', description: 'How real-time crew tracking in irrigation dispatch software shows where every truck is, what stop they are on, and which jobs are done — all day.', href: '/blogs/real-time-crew-tracking-irrigation-dispatch-software' },
  { title: 'Auto-Dispatching Recurring Seasonal Irrigation Service Visits', description: 'See how IrrigationBossPro auto-dispatches recurring winterization and start-up visits, builds routes, and texts customers without rebuilding the schedule each season.', href: '/blogs/recurring-seasonal-service-auto-dispatch-irrigation-software' },
  { title: 'Reducing No-Shows and Callbacks With Irrigation Dispatch Software', description: 'How irrigation dispatch software cuts no-shows and callbacks with confirmation texts, full job notes, parts lists, and routing for sprinkler crews.', href: '/blogs/reducing-no-shows-callbacks-irrigation-dispatch-software' },
  { title: 'Rerouting Crews Mid-Day When an Irrigation Job Runs Long', description: 'How irrigation dispatch software lets you reroute crews mid-day when a system install or valve repair runs long, without blowing up the rest of the schedule.', href: '/blogs/rerouting-crews-mid-day-irrigation-dispatch-software' },
  { title: 'The ROI of Irrigation Crew & Dispatch Software: What Contractors Save', description: 'See the real ROI of irrigation crew and dispatch software: more billable hours, faster invoicing, fewer missed seasonal jobs, and lower drive time for sprinkler crews.', href: '/blogs/roi-irrigation-crew-dispatch-software' },
  { title: 'Scaling From One to Five Irrigation Crews With Dispatch Software', description: 'See how IrrigationBossPro dispatch software lets an irrigation business grow from one crew to five without losing control of routes, parts, or seasonal service.', href: '/blogs/scaling-from-one-to-five-irrigation-crews-dispatch-software' },
  { title: 'Setting Up Irrigation Crew & Dispatch Software in Your First Week', description: 'A practical first-week setup plan for irrigation crew and dispatch software: load clients, build estimates, stock parts, and dispatch your first install or repair route.', href: '/blogs/setting-up-irrigation-crew-dispatch-software-first-week' },
  { title: 'Handling the Spring Start-Up Surge With Crew Dispatch Software', description: 'How crew dispatch software absorbs the spring start-up surge so you can batch, route, and assign hundreds of irrigation activations without a phone scramble.', href: '/blogs/spring-startup-dispatch-surge-irrigation-crew-software' },
  { title: 'Emergency Valve and Leak Repairs: Same-Day Crew Dispatch', description: 'See how irrigation dispatch software turns emergency valve and leak calls into same-day jobs with the right crew, parts, and a routed truck.', href: '/blogs/valve-repair-emergency-dispatch-irrigation-software' },
  { title: 'From Whiteboard to Dispatch Software: Modernizing Irrigation Crew Scheduling', description: 'How dispatch software replaces the whiteboard for irrigation crews, turning installs, repairs, backflow tests, and seasonal jobs into a live, routed schedule.', href: '/blogs/whiteboard-to-dispatch-software-irrigation-crews' },
];

const silo6 = [
  { title: 'Backflow Testing Invoices: Bill Test and Certification Fees Cleanly', description: 'How irrigation invoicing software itemizes backflow test fees, certification filings, and repair parts so every annual test bills cleanly and gets paid fast.', href: '/blogs/backflow-testing-invoices-certification-fees-software' },
  { title: 'Batch-Invoice an Entire Winterization Route in Minutes', description: 'See how irrigation software lets you batch-invoice a whole winterization route at once with flat-rate line items, card-on-file payments, and crew completion.', href: '/blogs/batch-invoice-winterization-route-irrigation-software' },
  { title: 'How to Bill Sprinkler Repairs the Same Day You Finish Them', description: 'Use IrrigationBossPro to invoice sprinkler repairs from the truck the same day, charge the card on file, and stop letting parts and labor slip away.', href: '/blogs/bill-sprinkler-repairs-same-day-with-software' },
  { title: 'Capture Every Part on the Invoice Before You Leave the Job', description: 'IrrigationBossPro lets your crew log every head, valve, and fitting on the invoice from the truck so no parts slip away and every install gets billed in full.', href: '/blogs/capture-parts-on-invoice-before-they-leave-the-job' },
  { title: 'Card-on-File Payments: Get Paid Faster on Every Irrigation Job', description: 'How card-on-file payments let irrigation businesses charge repairs, installs, winterizations, and start-ups the day the crew finishes &mdash; no chasing checks.', href: '/blogs/card-on-file-payments-irrigation-customers' },
  { title: 'Charge for Materials and Parts Markup on Irrigation Invoices', description: 'How to add heads, valves, controllers and pipe as line items with built-in markup so every irrigation invoice captures the parts margin you earned.', href: '/blogs/charge-materials-parts-markup-irrigation-invoices' },
  { title: 'From Deposit to Final Invoice: The Irrigation Install Billing Workflow', description: 'See how IrrigationBossPro runs an irrigation install from signed estimate and deposit to progress billing and a clean final invoice paid on file.', href: '/blogs/deposit-to-final-invoice-irrigation-install-workflow' },
  { title: 'Collecting Deposits and Down Payments on Irrigation Install Bids', description: 'How irrigation software ties a deposit to your approved line-item bid so materials are paid for and a card is on file before the crew ever digs.', href: '/blogs/deposits-and-down-payments-irrigation-install-bids' },
  { title: 'End-of-Season Billing: Collect Every Dollar Before Winter', description: 'See how irrigation software closes out your fall season fast: card-on-file charges, aging reports, automated reminders, and one-tap invoicing from the truck.', href: '/blogs/end-of-season-irrigation-billing-collect-before-winter' },
  { title: 'Invoicing Fall Winterizations and Blowouts at Scale', description: 'See how irrigation software invoices hundreds of fall winterizations and blowouts fast with card-on-file payments, flat-rate line items, and crew completion.', href: '/blogs/invoice-fall-winterization-blowouts-irrigation-software' },
  { title: 'Invoice From the Truck: Mobile Billing for Sprinkler Crews', description: 'See how mobile irrigation billing lets sprinkler crews invoice and collect card payments on site the moment a repair, blowout, or start-up is finished.', href: '/blogs/invoice-from-the-truck-irrigation-mobile-billing' },
  { title: 'Billing for Controller and Smart Timer Upgrades the Easy Way', description: 'How line-item estimates, parts tracking, and card-on-file invoicing make billing controller and smart timer upgrades fast, accurate, and paid same day.', href: '/blogs/irrigation-controller-and-smart-timer-upgrade-billing' },
  { title: 'Manual Invoicing vs. Software: The Real Cost for Irrigation Pros', description: 'Compare manual irrigation invoicing to billing software and see the real cost in lost parts, slow payments, and hours of admin IrrigationBossPro erases.', href: '/blogs/irrigation-invoicing-manual-vs-software-comparison' },
  { title: 'Irrigation Invoicing Software: The Complete Guide for Sprinkler Businesses', description: 'How irrigation invoicing software turns line-item estimates, parts, and seasonal service into fast, paid invoices with card-on-file for sprinkler businesses.', href: '/blogs/irrigation-invoicing-software-complete-guide' },
  { title: 'Flat-Rate vs. Time-and-Materials Billing for Sprinkler Service Calls', description: 'See how IrrigationBossPro lets you build flat-rate price-book bids or time-and-materials invoices for sprinkler service calls in minutes.', href: '/blogs/irrigation-service-call-flat-rate-vs-time-materials-billing' },
  { title: 'Line-Item Invoices That Show Every Head, Valve, and Foot of Pipe', description: 'How line-item invoicing software itemizes every sprinkler head, valve, controller, and foot of pipe so irrigation customers see exactly what they paid for.', href: '/blogs/line-item-invoices-irrigation-heads-valves-pipe' },
  { title: 'Billing Prepaid Seasonal Packages: Start-Up, Mid-Season, Blowout', description: 'See how irrigation billing software sells prepaid seasonal packages and bills start-up, mid-season, and blowout visits cleanly against money customers paid up front.', href: '/blogs/prepaid-seasonal-irrigation-packages-billing-software' },
  { title: 'How Professional Invoices Win Repeat Irrigation Customers', description: 'How clear, itemized irrigation invoices with parts, labor, and card-on-file payments build the trust that turns one-time repairs into repeat seasonal clients.', href: '/blogs/professional-irrigation-invoices-win-repeat-customers' },
  { title: 'Progress Billing for Multi-Day Irrigation System Installs', description: 'How progress billing software invoices multi-day irrigation installs in stages &mdash; deposit, rough-in, and final &mdash; so cash flows in as the project moves.', href: '/blogs/progress-billing-irrigation-system-installs' },
  { title: 'Recurring Billing for Seasonal Irrigation Service Plans', description: 'How recurring billing in irrigation software charges seasonal service plans automatically so winterizations, start-ups, and backflow tests get paid without chasing invoices.', href: '/blogs/recurring-billing-seasonal-irrigation-service-plans' },
  { title: 'Cut Unpaid Invoices With Automated Payment Reminders', description: 'How automated payment reminders help irrigation businesses collect on repairs, installs, winterizations, and start-ups &mdash; without chasing overdue invoices by hand.', href: '/blogs/reduce-unpaid-irrigation-invoices-automated-reminders' },
  { title: 'The ROI of Irrigation Invoicing Software on Your Cash Flow', description: 'See how irrigation invoicing software speeds up payment, cuts unbilled jobs, and steadies cash flow through winterization and spring start-up season.', href: '/blogs/roi-of-irrigation-invoicing-software-cash-flow' },
  { title: 'Splitting Invoices for Property Managers With Multiple Sites', description: 'How IrrigationBossPro splits irrigation invoices across multiple sites for property managers, with line-item detail per location and one clean statement.', href: '/blogs/split-invoices-property-managers-multi-site-irrigation' },
  { title: 'Spring Start-Up Billing: Invoice an Entire Route in a Morning', description: 'See how irrigation software turns a full day of spring start-up appointments into a stack of paid invoices you can send before lunch, with cards on file.', href: '/blogs/spring-startup-billing-irrigation-software' },
  { title: 'Why Paper Invoices Are Costing Your Irrigation Business Money', description: 'Paper invoices slow irrigation cash flow and bury parts costs. See how IrrigationBossPro invoicing with card-on-file payments gets you paid faster.', href: '/blogs/stop-using-paper-invoices-irrigation-business' },
  { title: 'Sync Irrigation Invoices to QuickBooks Without Double Entry', description: 'Push irrigation invoices, parts line items, and card payments to QuickBooks automatically so your books match the field without re-typing a single number.', href: '/blogs/sync-irrigation-invoices-quickbooks-accounting' },
  { title: 'Text the Invoice, Get Paid: SMS Billing for Irrigation Jobs', description: 'See how IrrigationBossPro texts invoices with a pay link the moment a sprinkler job wraps, so card-on-file payments land faster.', href: '/blogs/text-irrigation-invoices-to-customers-get-paid' },
  { title: 'Know Exactly Which Irrigation Invoices Are Overdue', description: 'See every overdue irrigation invoice at a glance with an aging report so you stop guessing who owes you for installs, repairs, and winterizations.', href: '/blogs/track-overdue-irrigation-invoices-aging-report' },
  { title: 'Turn Irrigation Estimates Into Invoices With One Click', description: 'How IrrigationBossPro converts an approved sprinkler estimate &mdash; heads, valves, controllers, pipe, labor &mdash; into a finished invoice in one click, with no re-keying.', href: '/blogs/turn-irrigation-estimates-into-invoices-one-click' },
  { title: 'Handling Warranty and Callback Visits Without Billing Headaches', description: 'See how irrigation software tracks warranty and callback visits, separates no-charge work from billable add-ons, and keeps your margins clean on every return trip.', href: '/blogs/warranty-and-callback-irrigation-billing-no-charge-jobs' },
];

const silo7 = [
  { title: 'Submitting Backflow Reports to the Water Authority with Irrigation Business Software', description: 'See how irrigation business software captures backflow test results, generates clean reports, and gets them to the water authority on time every season.', href: '/blogs/backflow-report-submission-water-authority-irrigation-business-software' },
  { title: 'How Irrigation Business Software Tracks Backflow Testing &amp; Certification Deadlines', description: 'See how irrigation business software tracks backflow test due dates and certification deadlines so you never miss a required test or lose a recurring customer.', href: '/blogs/backflow-testing-certification-tracking-irrigation-business-software' },
  { title: 'Capturing Add-On Repairs During a Service Call with Irrigation Business Software', description: 'See how irrigation business software turns broken heads and stuck valves found on a service call into approved, invoiced add-on repairs before the truck leaves.', href: '/blogs/capturing-add-on-repairs-during-service-irrigation-business-software' },
  { title: 'Card-on-File Billing for Repeat Winterization Customers in Irrigation Business Software', description: 'See how irrigation business software stores a card on file so repeat winterization customers get billed automatically the day the blowout is done.', href: '/blogs/card-on-file-seasonal-billing-irrigation-business-software' },
  { title: 'Keeping Controller Programming &amp; Settings on File in Irrigation Business Software', description: 'Store every controller&apos;s zones, run times, and wiring in irrigation business software so winterizations, start-ups, and repairs go faster.', href: '/blogs/controller-programming-service-records-irrigation-business-software' },
  { title: 'Handling Day-Of Dispatch Changes for Irrigation Crews in Irrigation Business Software', description: 'See how irrigation business software lets you reroute crews, swap jobs, and text customers the moment your dispatch plan changes mid-day.', href: '/blogs/crew-dispatch-day-of-changes-irrigation-business-software' },
  { title: 'Letting Customers Self-Schedule Winterizations with Irrigation Business Software', description: 'Let homeowners book their own fall blowouts online&mdash;see how irrigation business software fills your winterization calendar without the phone marathon.', href: '/blogs/customer-self-scheduling-winterization-irrigation-business-software' },
  { title: 'On-My-Way Customer Texts for Irrigation Crews with Irrigation Business Software', description: 'See how automated on-my-way texts in irrigation business software cut no-shows, keep customers informed, and tighten crew dispatch on every service call.', href: '/blogs/customer-texts-on-the-way-irrigation-business-software' },
  { title: 'Collecting Deposits &amp; Progress Payments on Installs with Irrigation Business Software', description: 'Use irrigation business software to collect install deposits, bill progress payments by milestone, and keep card-on-file invoicing on track all season.', href: '/blogs/deposit-progress-billing-installs-irrigation-business-software' },
  { title: 'End-of-Season Revenue &amp; Service Reporting in Irrigation Business Software', description: 'See how irrigation business software turns a full season of installs, repairs, backflow tests, and winterizations into clean revenue and service reports.', href: '/blogs/end-of-season-revenue-reporting-irrigation-business-software' },
  { title: 'Booking a Full Fall Winterization Season with Irrigation Business Software', description: 'See how irrigation business software books a full fall winterization season&mdash;recurring jobs, routed crews, deposits, and card-on-file blowout invoicing.', href: '/blogs/fall-winterization-blowout-scheduling-irrigation-business-software' },
  { title: 'Shrinking Quote-to-Cash Time for Sprinkler Jobs with Irrigation Business Software', description: 'See how irrigation business software shortens quote-to-cash on sprinkler jobs with fast line-item bids, materials tracking, scheduling, and card-on-file payments.', href: '/blogs/faster-quote-to-cash-irrigation-business-software' },
  { title: 'Your First Week Setting Up Irrigation Business Software: A Practical Checklist', description: 'A practical first-week checklist for setting up irrigation business software so your clients, parts, estimates, schedule, and seasonal service are dialed in fast.', href: '/blogs/first-software-setup-checklist-irrigation-business-software' },
  { title: 'Good-Better-Best Install Estimates That Close with Irrigation Business Software', description: 'Build good-better-best sprinkler install bids with line-item materials and tiers in irrigation business software so more new-system estimates actually close.', href: '/blogs/good-better-best-install-estimates-irrigation-business-software' },
  { title: 'Working the Job Board for Unassigned Sprinkler Repairs in Irrigation Business Software', description: 'How the IrrigationBossPro Job Board turns unassigned sprinkler repairs into quoted, scheduled, dispatched, and invoiced work in irrigation business software.', href: '/blogs/job-board-unassigned-repairs-irrigation-business-software' },
  { title: 'Spreadsheets vs. Irrigation Business Software for a Growing Sprinkler Company', description: 'See why a growing sprinkler company outgrows spreadsheets and how irrigation business software handles bids, parts, scheduling, and seasonal service.', href: '/blogs/manual-spreadsheets-vs-irrigation-business-software' },
  { title: 'Marking Up Heads, Valves &amp; Pipe Correctly with Irrigation Business Software', description: 'Stop guessing on parts margins. See how irrigation business software builds correct markup on heads, valves and pipe into every estimate and invoice.', href: '/blogs/materials-markup-pricing-irrigation-business-software' },
  { title: 'Scheduling Multi-Day Install Projects with Irrigation Business Software', description: 'See how irrigation business software schedules multi-day sprinkler installs, blocks crews, stages materials, and keeps every zone phase on track.', href: '/blogs/multi-day-install-project-scheduling-irrigation-business-software' },
  { title: 'Building Accurate New System Install Bids in Irrigation Business Software', description: 'How irrigation business software builds accurate, material-loaded new system install bids that win sprinkler jobs, protect margin, and convert straight to scheduled work.', href: '/blogs/new-system-install-bids-irrigation-business-software' },
  { title: 'Tracking Truck Stock &amp; Reordering Irrigation Parts with Irrigation Business Software', description: 'See how irrigation business software tracks truck stock and parts usage so crews never run out of heads, valves, or controllers and reordering happens on time.', href: '/blogs/parts-truck-stock-reorder-irrigation-business-software' },
  { title: 'Reusable Per-Zone &amp; Per-Head Pricing Templates in Irrigation Business Software', description: 'Build reusable per-zone and per-head pricing templates in irrigation business software so every sprinkler bid is fast, accurate, and consistent.', href: '/blogs/per-zone-pricing-templates-irrigation-business-software' },
  { title: 'Property Profiles That Remember Every Sprinkler System with Irrigation Business Software', description: 'Property profiles in irrigation business software store every controller, valve, head, and backflow device so your crew shows up knowing the whole system.', href: '/blogs/property-profiles-system-history-irrigation-business-software' },
  { title: 'Cutting Callbacks with Warranty &amp; Repair History in Irrigation Business Software', description: 'See how irrigation business software tracks warranty terms and full repair history per property so you cut unpaid callbacks and bill warranty work the right way.', href: '/blogs/reduce-callbacks-warranty-tracking-irrigation-business-software' },
  { title: 'The Real ROI &amp; Payback of Switching to Irrigation Business Software', description: 'A concrete look at the real ROI and payback period of irrigation business software: hours saved, install margin protected, and seasonal revenue recaptured.', href: '/blogs/roi-payback-irrigation-business-software' },
  { title: 'Automating Winterization &amp; Start-Up Renewal Campaigns in Irrigation Business Software', description: 'How irrigation business software auto-builds winterization and spring start-up renewal campaigns so every customer gets rebooked, texted, and invoiced on time.', href: '/blogs/seasonal-service-renewal-campaigns-irrigation-business-software' },
  { title: 'Batching Spring Start-Up Routes Faster with Irrigation Business Software', description: 'See how irrigation business software batches spring start-up routes&mdash;clustering jobs by neighborhood, dispatching crews, and texting customers in one pass.', href: '/blogs/spring-start-up-route-batching-irrigation-business-software' },
  { title: 'Line-Item Sprinkler Head &amp; Valve Repair Invoicing in Irrigation Business Software', description: 'Line-item sprinkler head and valve repair invoicing in irrigation business software keeps every part on the bill, protects margin, and gets repairs paid faster.', href: '/blogs/sprinkler-head-valve-repair-invoicing-irrigation-business-software' },
  { title: 'Documenting Valve Locating &amp; Mainline Leak Jobs in Irrigation Business Software', description: 'See how irrigation business software documents valve locating and mainline leak jobs &mdash; notes, photos, parts, and estimates tied to the property profile.', href: '/blogs/valve-locating-mainline-leak-jobs-irrigation-business-software' },
  { title: 'Standardizing Blowout Checklists Across Crews with Irrigation Business Software', description: 'See how irrigation business software puts the same blowout checklist on every crew&apos;s phone so winterizations are consistent, complete, and fully billed.', href: '/blogs/winterization-blowout-checklists-irrigation-business-software' },
  { title: 'Turning a Zone-by-Zone System Audit into an Estimate with Irrigation Business Software', description: 'See how irrigation business software turns a zone-by-zone system audit into a clean line-item estimate with the right parts, labor, and seasonal service attached.', href: '/blogs/zone-by-zone-system-audit-estimates-irrigation-business-software' },
];

export default function BlogIndexPage() {
  return (
    <BlogShell>
      <div className="blog-index">
        <h1>Irrigation Business Software Blog</h1>
        <p className="blog-index-sub">Guides on estimating, scheduling, sprinkler repair, backflow testing, dispatch, billing, and growing an irrigation business.</p>

        <h2 className="blog-index-silo-title">Irrigation Software</h2>
        <div className="blog-index-grid">
          {silo0.map((post) => (
            <a key={post.href} href={post.href} className="blog-index-card"><h3>{post.title}</h3><p>{post.description}</p></a>
          ))}
        </div>

        <h2 className="blog-index-silo-title">Sprinkler Repair Software</h2>
        <div className="blog-index-grid">
          {silo1.map((post) => (
            <a key={post.href} href={post.href} className="blog-index-card"><h3>{post.title}</h3><p>{post.description}</p></a>
          ))}
        </div>

        <h2 className="blog-index-silo-title">Irrigation Scheduling Software</h2>
        <div className="blog-index-grid">
          {silo2.map((post) => (
            <a key={post.href} href={post.href} className="blog-index-card"><h3>{post.title}</h3><p>{post.description}</p></a>
          ))}
        </div>

        <h2 className="blog-index-silo-title">Irrigation Estimating Software</h2>
        <div className="blog-index-grid">
          {silo3.map((post) => (
            <a key={post.href} href={post.href} className="blog-index-card"><h3>{post.title}</h3><p>{post.description}</p></a>
          ))}
        </div>

        <h2 className="blog-index-silo-title">Backflow Testing Software</h2>
        <div className="blog-index-grid">
          {silo4.map((post) => (
            <a key={post.href} href={post.href} className="blog-index-card"><h3>{post.title}</h3><p>{post.description}</p></a>
          ))}
        </div>

        <h2 className="blog-index-silo-title">Irrigation Crew &amp; Dispatch Software</h2>
        <div className="blog-index-grid">
          {silo5.map((post) => (
            <a key={post.href} href={post.href} className="blog-index-card"><h3>{post.title}</h3><p>{post.description}</p></a>
          ))}
        </div>

        <h2 className="blog-index-silo-title">Irrigation Invoicing &amp; Billing</h2>
        <div className="blog-index-grid">
          {silo6.map((post) => (
            <a key={post.href} href={post.href} className="blog-index-card"><h3>{post.title}</h3><p>{post.description}</p></a>
          ))}
        </div>

        <h2 className="blog-index-silo-title">Irrigation Business Software</h2>
        <div className="blog-index-grid">
          {silo7.map((post) => (
            <a key={post.href} href={post.href} className="blog-index-card"><h3>{post.title}</h3><p>{post.description}</p></a>
          ))}
        </div>
      </div>
    </BlogShell>
  );
}
